### ISSUE TITLE
FizzBuzz exercise is missing (empty file)

### ISSUE THREAD

**Issue by andybalaam** [tweedegolf/teach-rs#112]
The file https://github.com/tweedegolf/teach-rs/blob/main/content/mods/B-crate-engineering/topics/testing/exercises/fizzbuzz/description.md is empty.

The content seems to have been deleted in https://github.com/tweedegolf/teach-rs/commit/cb6390e27a286e86d279cde8c59b77adcf579d43

**Comment by hdoordt** [comment]
Thank you for pointing that out @andybalaam
